parameters:
    axstrad.admin.page.class: Axstrad\Bundle\PageAdminBundle\Admin\PageAdmin

services:
    axstrad.admin.page:
        class: %axstrad.admin.page.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Page" }
        arguments:
            - ~
            - Axstrad\Bundle\PageBundle\Entity\Page
            - ~
        calls:
            - [ setTranslationDomain, [AxstradPageAdminBundle]]
            - [ setObjectManager, [@doctrine.orm.entity_manager]]
