language: php
php:
  - 5.5
  - 5.4
env:
  - SYMFONY_VERSION="2.3.*"
  - SYMFONY_VERSION="2.4.*"
  - SYMFONY_VERSION="2.5.*"
  - SYMFONY_VERSION="dev-master"
before_script:
  - composer install --prefer-source --dev
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}
script:
  - phpunit -c phpunit.dist.xml

notifications:
  email:
    - dev@dankempster.co.uk
