Axstrad\Component\Page\Entity\BasePage:
    type: mappedSuperclass
    fields:
        slug:
            type: string
            length: 128
            gedmo:
                slug:
                    separator: -
                    style: lower
                    fields:
                        - heading
    oneToOne:
        seoMetadata:
            targetEntity: Symfony\Cmf\Bundle\SeoBundle\Model\SeoMetadata
            joinColumn:
                name: seoMetadataId
                referencedColumnName: id
                onDelete: CASCADE
    indexes:
        search_idx:
            columns: slug

